# .github/workflows/deploy.yml
name: Build & Deploy to CapRover

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GHCR }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/hugoorielso/dimcultura-frontend:production
          no-cache: true
          build-args: |
            API_URL=${{ secrets.API_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_API_IMAGES=${{ secrets.NEXT_PUBLIC_API_IMAGES }}
            BUILD_ID=${{ github.run_number }}

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: ${{ secrets.CAPROVER_SERVER }}
          app: ${{ secrets.CAPROVER_APP_NAME }}
          token: ${{ secrets.CAPROVER_APP_TOKEN }}
          image: ghcr.io/hugoorielso/dimcultura-frontend:production